name: CI

on:
  push:
      branches:
      - actions-lab

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup
      uses: warrenbuckley/Setup-Nuget@v1
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Nuget Restore
      working-directory: src/WorkItemMigrator
      run: nuget restore     
      
    - name: MSBuild
      working-directory: src/WorkItemMigrator
      run: msbuild WorkItemImport/wi-import.csproj

